packages:
  - "."

minimumReleaseAge: 1440
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 525600
trustLockfile: false
blockExoticSubdeps: true
strictDepBuilds: true

allowBuilds:
  electron: true
  esbuild: true
